<a href="https://colab.research.google.com/github/MohammadHonor/NumpyLearningCode/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("numpy hidiidi")

In [ ]:
import numpy as np
a = np.array([4, 8, 12])
b =np.array([1.2, 1, 1])
a+b
a-b
a*b
a/b
a//b
3*b
np.dot(a,b)
v1=np.array([1,-2,3])
v2=np.array([4,0,-1])
v1+v2

array([ 5, -2,  2])

In [ ]:
import numpy as np
a = np.array([3,4])
v =np.linalg.norm(a)
u = a/v
v1 = np.array([5,0])
u = v1/np.linalg.norm(v1)
print(u)

[1. 0.]


In [ ]:
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[1,2],
              [3,4],
              [5,6]])

A @ B
m = np.matmul(A,B)
m


array([[22, 28],
       [49, 64]])

Identity matris

In [ ]:
I=np.eye(3)
I.T
A = np.array([[22, 28],
       [49, 64]])
A.T



array([[22, 49],
       [28, 64]])

**Determinants**

In [ ]:
import numpy as np
A = np.array([[22, 28],
       [49, 64]])
np.linalg.inv(A)

array([[ 1.77777778, -0.77777778],
       [-1.36111111,  0.61111111]])

In [ ]:
from datetime import datetime,date,timedelta,timezone
d1 = date(2025, 11, 23)
today = date.today()
print(d1.day,today.day,d1.weekday(),d1.isoweekday())
print(type(d1))
d2= datetime.utcnow()
print(d2)
utc = datetime.now(timezone.utc)
print(utc.astimezone())




23 25 6 7
<class 'datetime.date'>
2025-11-25 01:56:57.534433
2025-11-25 01:56:57.534511+00:00


In [ ]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])
A+B
dot_product = np.dot(A,B)
print("dot product is ",dot_product)
matrix_mult = A@B
print("matrix multiplication =",matrix_mult)

dot product is  [[19 22]
 [43 50]]
matrix multiplication = [[19 22]
 [43 50]]


In [ ]:
I = np.eye(4)
a = np.zeros(4)
I.dot(a)
np.linalg.matrix_rank(B)

2

In [ ]:
A = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [1, 1, 2]
])
det = np.linalg.det(A)
det
minor = np.linalg.det(A[[0,2]][:, [0,1]])
print(minor)
A[[0,2]][:,[0,1]]
A[[0,1]][:,[1,2]]
u,s,vt = np.linalg.svd(A)
print(u,s,vt)

-1.0
[[-4.29710769e-01 -1.23889688e-01 -8.94427191e-01]
 [-8.59421538e-01 -2.47779376e-01  4.47213595e-01]
 [-2.77025764e-01  9.60862491e-01 -1.32965232e-15]] [8.70644108e+00 4.44841159e-01 2.09736364e-16] [[-0.27859599 -0.5253735  -0.8039695 ]
 [ 0.76749654 -0.62501948  0.14247706]
 [-0.57735027 -0.57735027  0.57735027]]


In [ ]:
lin_s = np.linspace(1,20,num=10)
print(lin_s)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [ ]:
v1 = np.random.rand(2,3,4)
v1
v2 = np.random.randn(3,4,3)
v2
v3 = np.random.ranf(3)
v3
v4 = np.random.random_sample(3)
v4
v5 = np.random.randint(1,5,dim=3)
v5

NameError: name 'np' is not defined

Braodcasting****

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])
C = A + b
print(C)

print(C[1:,1:2])


[[11 22 33]
 [14 25 36]]
[[25]]


 Fency Indexing****

In [ ]:
import numpy as np

A = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [34, 56, 23],
    [70, 80, 90]
])

print(A[[0,1,2]])
print("*"*20)
print(A[:,[1,2]])
print("*"*20)
print(A[[1,2],[1,2]])
print("*"*20)
print(A[A>20])
print("*"*20)

r = [0,1,2]
c = [2,1,0]
print(A[r,c])

[[10 20 30]
 [40 50 60]
 [34 56 23]]
********************
[[20 30]
 [50 60]
 [56 23]
 [80 90]]
********************
[50 23]
********************
[30 40 50 60 34 56 23 70 80 90]
********************
[30 50 34]


In [ ]:
ls = np.arange(16)
ls2 = ls*ls
print(ls2[2:9])
arr = ls.reshape(4,4)
np.linalg.eig(arr)
# arr.strides
# np.sin(np.linspace(0, np.pi, 5))



[ 4  9 16 25 36 49 64]


EigResult(eigenvalues=array([ 3.24642492e+01, -2.46424920e+00,  5.17733364e-17, -1.23030121e-15]), eigenvectors=array([[-0.11417645, -0.7327781 ,  0.02390128, -0.46422674],
       [-0.3300046 , -0.28974835,  0.37599103,  0.83562736],
       [-0.54583275,  0.15328139, -0.8236859 , -0.2785745 ],
       [-0.76166089,  0.59631113,  0.42379359, -0.09282612]]))

In [ ]:
a = np.arange(3)
b = np.arange(4)
np.outer(a, b)
np.outer(b,a)
a[:,np.newaxis]
print(np.newaxis)


None


In [ ]:
B = np.zeros((1, 3, 1, 4))
print(B)
B.squeeze().shape

[[[[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]

  [[0. 0. 0. 0.]]]]


(3, 4)

In [ ]:
img = np.random.rand(28,28)
cimg = img.reshape(1,-1)
cimg

NameError: name 'np' is not defined

In [ ]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)
a,b

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([0, 1, 2]))

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(4)
a,b
a+b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)
a,b
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
a = np.arange(12).reshape(12,1)
b = np.arange(4).reshape(4)
a,b
a+b

NameError: name 'np' is not defined

In [ ]:
x = np.array([[1,2,3],[4,5,6]])

np.repeat(x, 4)
np.tile(x, (3,2))
# np.expand_dims(x, axis=0)
# 3 most important operations in

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
import numpy as np
np.repeat(3, 4)
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)
np.repeat(x, 3, axis=1)
np.repeat(x, [1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])